input = "src"
output = "out"

[options]
include = [
    ".darklua.json5",
    ".luaurc",
    "pesde.toml",
    "pesde.lock",
    "LICENSE",
    "README.md",
    "roblox_packages/**/*",
    "*.project.json",
    "sourcemap.json",
    "plugin/**/*",
]
darklua_config = ".darklua.json5"
temp_dir_keep = false
temp_dir_location = "." # Makes pesde cli tools work

[options.scripts]
preProcess = [
    "pesde install",
    "rojo sourcemap test.project.json -o sourcemap.json",
]
